name: Contributor License Agreement (CLA)

on: workflow_dispatch

jobs:
  cla:
    runs-on: ubuntu-latest
    if: |
      (github.event.issue.pull_request
        && !github.event.issue.pull_request.merged_at
        && contains(github.event.comment.body, 'signed')
      )
      || (github.event.pull_request
        && !github.event.pull_request.merged
        && !contains(github.event.commits.*.message, '[ci] release')
        && !contains(github.event.commits.*.message, '[ci] Update package-lock.json')
      )
    steps:
      - uses: Shopify/shopify-cla-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cla-token: ${{ secrets.CLA_TOKEN }}
