name: Tests and Lint

on:
  push:
    branches:
      - '[0-9]+-[0-9]+'
      # - 'v[0-9].[0-9].x-[0-9]+-[0-9]+'
  pull_request:
    branches:
      - '[0-9]+-[0-9]+'
      # - 'v[0-9].[0-9].x-[0-9]+-[0-9]+'

concurrency:
  group: hydrogen-${{ github.head_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # strategy:
    #   matrix:
    #     # os: [windows-latest, ubuntu-latest]
    #     os: [ubuntu-latest]
    #     node-version: [16.x, 18.x]

    # name: OS ${{ matrix.os }} / NodeJS ${{ matrix.node-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install the packages
        run: yarn install --frozen-lockfile

      - name: Run CI checks
        run: yarn ci:checks

      - name: Build the code
        run: yarn build
